---
general:
  buildTool: "mta"

stages:
  Build:
    mavenExcuteStaticCodeChecks: false
    npmExecuteLint: true
  
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10.hana.ondemand.com"
    cfOrg: "4f0177b8trial"
    cfSpace: "dev"
    cfAppName: "invoiceservice"
    cfCredentialsId: "deploy-to-cf"
    uiVeri5ExecuteTests: false

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10.hana.ondemand.com"
    cfOrg: "4f0177b8trial"
    cfSpace: "dev"
    cfAppName: "invoiceservice"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: false

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  npmExecuteLint:
    failOnError: true
  
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  tmsUpload:
    nodeName: "qas1"
    credentialsId: "tms-sk"
